### PR TITLE
Adding assess

### PR DESCRIPTION
**Pull request by phil-fradkin**
Assess module still have to finish figuring out Parent of Gene (Orn score)

### CODE REVIEW

**Comment by thejmazz** [comment]
There's a few conflicts from your branch with updated versions of some files:

```
~/r/Ontoscope$ git merge --no-ff Adding-asses
warning: Cannot merge binary files: phylify/COdat.RData (HEAD vs. Adding-asses)
Auto-merging phylify/workflow.r
CONFLICT (content): Merge conflict in phylify/workflow.r
Auto-merging phylify/COdat.RData
CONFLICT (add/add): Merge conflict in phylify/COdat.RData
Auto-merging fantom_import/fantom_main.R
CONFLICT (content): Merge conflict in fantom_import/fantom_main.R
Automatic merge failed; fix conflicts and then commit the result.
```

`--no-ff` is for no fast forward and makes a new merge commit from what I understand.

My files, and then one of @biodim's.

I am replacing them with whatever is on the latest commit on master:

``` bash
git checkout HEAD -- fantom_import/fantom_main.R
git checkout HEAD -- phylify/workflow.r
git checkout HEAD -- phylify/COdat.RData
```

Overall, fairly clean merge :) If someone got to this earlier, I think it would have been mergeable from the web interface.

Feel free to commit directly to master from now on though.

**Comment by thejmazz** [comment]
@MonumentalJ I'll let you delete the branch when you're ready.

**Comment by phil-fradkin** [comment]
Hey Julian so what do I have to do? I just want to add asses I don't really
want all the other changes

**Comment by thejmazz** [comment]
Yeah it's fine, just check if the current master has everything how you want it

**Pull request merged**
